# Generated by Django 5.2 on 2025-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_qr_code_ticket_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата использования'),
        ),
    ]
