# Generated by Django 5.2 on 2025-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_cointransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_code_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
