# Generated by Django 5.2 on 2025-04-10 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='events/images/', verbose_name='Изображение')),
                ('target_audience', models.CharField(max_length=200, verbose_name='Для кого')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('coins_reward', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ЛЭТИ-коины')),
                ('significance_level', models.CharField(choices=[('legendary', 'Легендарный'), ('epic', 'Эпический'), ('normal', 'Обычный')], default='normal', max_length=10, verbose_name='Уровень значимости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-date'],
            },
        ),
    ]
