# Generated by Django 5.2 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('competition', 'Соревнование'), ('hackathon', 'Хакатон'), ('meetup', 'Встреча'), ('lecture', 'Лекция'), ('workshop', 'Мастер-класс'), ('conference', 'Конференция'), ('cultural', 'Культурное мероприятие'), ('sport', 'Спортивное событие')], default='meetup', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
