# Generated by Django 5.2 on 2025-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Default Organizer', max_length=200, verbose_name='Организатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на организатора'),
        ),
    ]
