# Generated by Django 5.2 on 2025-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizer_event_organizer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_type',
            field=models.CharField(choices=[('professional', 'Профессионально-ориентированная деятельность'), ('scientific', 'Научно-образовательная деятельность'), ('patriotic', 'Патриотическая и гражданско-правовая деятельность'), ('cultural_creative', 'Культурно-творческая деятельность'), ('spiritual', 'Духовно-нравственная деятельность'), ('sports_health', 'Физкультурно-оздоровительная деятельность и воспитание здорового образа жизни'), ('student_government', 'Развитие студенческого самоуправления'), ('volunteering', 'Поддержка и развитие волонтёрской деятельности'), ('ecological', 'Экологическая деятельность'), ('tolerance', 'Воспитание толерантности')], default='scientific', max_length=20, verbose_name='Вид деятельности'),
        ),
    ]
