# Generated by Django 5.2 on 2025-04-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год'), ('all', 'Весь период')], default='all', max_length=10)),
                ('total_registered', models.PositiveIntegerField(default=0)),
                ('total_attended', models.PositiveIntegerField(default=0)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='events.event')),
            ],
            options={
                'verbose_name': 'Статистика мероприятия',
                'verbose_name_plural': 'Статистика мероприятий',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
