# Generated by Django 5.2 on 2025-04-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('events', '0004_event_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstats',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventstats',
            name='calculation_date',
        ),
        migrations.RemoveField(
            model_name='eventstats',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventstats',
            name='period',
        ),
        migrations.AddField(
            model_name='eventstats',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventstats',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='events.event'),
        ),
    ]
