# Generated by Django 5.2 on 2025-04-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_eventstats_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventStats',
        ),
    ]
